workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: europe-north1-docker.pkg.dev/psychic-iridium-484208-c3/ml-images/train-image:latest
      args:
        - --data_dir=data/time_series
        - --max_epochs=2
        - --batch_size=8
